### ISSUE TITLE
Help with ROI

### ISSUE THREAD

**Issue by fmaeda** [itzMeerkat/flutter_image_map#1]
Hi, 

Seems like the ROI Select Tool is down (http://www.jiayizhang.me).

I would love to try your lib in my project. Do you have any alternative to help with the mappings?

Thanks for your work.

**Comment by itzMeerkat** [comment]
Thank you for your interest!
The source code of the web tool is also in this repo (index.html in root folder). You can open it directly in browser since it won't communicate with any remote server.

**Comment by fmaeda** [comment]
Thanks!
