### ISSUE TITLE
Does not support null safety 

### ISSUE THREAD

**Issue by AhmedSiddiquibBenchMatrix** [itzMeerkat/flutter_image_map#2]
Does not support null safety you need to remove null safety code from flutter which is not good

**Comment by itzMeerkat** [comment]
Just updated, glad to find this package useful!

**Comment by AhmedSiddiquibBenchMatrix** [comment]
> Just updated, glad to find this package useful!

Thank you for your quick response . Yeah it was very useful for my project.
